# Generated by Django 6.1.1 on 2026-09-22 10:05

import Apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_remove_salonemployee_chair_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=63, unique=True)),
                ('join_token', models.CharField(default=Apps.tenants.models.new_join_token, max_length=43, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='users.barberprofile')),
                ('salon', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='users.salon')),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='CustomerTenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-joined_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber_profile__isnull', True), ('salon__isnull', False)), models.Q(('barber_profile__isnull', False), ('salon__isnull', True)), _connector='OR'), name='tenant_has_exactly_one_business'),
        ),
        migrations.AddConstraint(
            model_name='customertenantmembership',
            constraint=models.UniqueConstraint(fields=('customer', 'tenant'), name='unique_customer_tenant_membership'),
        ),
    ]
