# Generated by Django 6.1.1 on 2026-09-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='debug_code',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
    ]
