# Generated by Django 6.1.1 on 2026-09-14 09:57

import Apps.common.images
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('users', '0002_otpcode_debug_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='accepting_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='avatar',
            field=Apps.common.images.ImageRefField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbers', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='cover_image',
            field=Apps.common.images.ImageRefField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='experience_range',
            field=models.CharField(choices=[('under_1', 'Less than a year'), ('1_3', '1-3 years'), ('3_5', '3-5 years'), ('5_10', '5-10 years'), ('10_plus', '10 years or more')], default='under_1', max_length=10),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='tiktok',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='title',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=Apps.common.images.ImageRefField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='salon',
            name='auto_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='avatar',
            field=Apps.common.images.ImageRefField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='bio',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='salon',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='salon',
            name='cover_image',
            field=Apps.common.images.ImageRefField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salon',
            name='private_booth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salon',
            name='tagline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salon',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salon',
            name='verification',
            field=models.CharField(choices=[('unverified', 'Not submitted'), ('pending', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=12),
        ),
        migrations.AddField(
            model_name='salon',
            name='women_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salonemployee',
            name='chair_status',
            field=models.CharField(choices=[('at_chair', 'At the chair'), ('on_break', 'On a break'), ('off_duty', 'Off duty')], default='at_chair', max_length=10),
        ),
        migrations.AddField(
            model_name='salonemployee',
            name='commission_rate',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='salonemployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='barberprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(70)]),
        ),
    ]
