# Generated by Django 6.1.1 on 2026-09-14 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_barberprofile_accepting_clients_barberprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberprofile',
            name='auto_accept',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='barberprofile',
            name='cancellation_window_hours',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='salon',
            name='cancellation_window_hours',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(168)]),
        ),
    ]
