# Generated by Django 6.1.1 on 2026-09-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_barberprofile_auto_accept_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='licence_number',
        ),
        migrations.AlterField(
            model_name='salon',
            name='verification',
            field=models.CharField(choices=[('unverified', 'Not reviewed'), ('pending', 'Under review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=12),
        ),
    ]
