# Generated by Django 6.1.1 on 2026-09-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_salon_licence_number_alter_salon_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonemployee',
            name='chair_status',
        ),
    ]
