# Generated by Django 6.1.1 on 2026-10-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # After the seed, so every value already in the column names a real tier.
    dependencies = [
        ('subscriptions', '0002_seed_tiers'),
        ('users', '0007_user_account_status_user_subscription_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription_tier',
            field=models.ForeignKey(db_column='subscription_tier', on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.subscriptiontier', to_field='slug'),
        ),
    ]
