# Generated by Django 6.1.1 on 2026-10-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_subscription_tier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='try_on_credits',
        ),
    ]
