"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.1, then extended
with the authentication stack: a phone-based user model, JWT sessions, OTP
verification and the SMS provider that delivers the codes.

Every security-sensitive value reads from the environment so nothing secret
lives in this file. `.env.example` lists what has to be set; `.env` is read on
startup when present and is not committed.
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


def env(name: str, default: str = '') -> str:
    """A variable that is present but blank counts as unset.

    `.env` files are full of `KEY=` lines waiting to be filled in, and taking
    those literally is how an empty signing key reaches the JWT encoder.
    """
    value = os.environ.get(name, '').strip()
    return value or default


def env_bool(name: str, default: bool = False) -> bool:
    return env(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


def env_int(name: str, default: int) -> int:
    raw = env(name).strip()
    return int(raw) if raw else default


def env_list(name: str, default: str = '') -> list[str]:
    return [item.strip() for item in env(name, default).split(',') if item.strip()]



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY', 'django-insecure-3ph75(^hmg(a90oav)n08cj*=$==y$&r82as(+p*r#9%v_&%tg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    # First, so `manage.py runserver` serves ASGI and answers WebSockets.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'Apps.tenants',
    'Apps.users',
    'Apps.services',
    'Apps.schedules',
    'Apps.portfolio',
    'Apps.directory',
    'Apps.bookings',
    'Apps.reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
# Bookings are pushed to the dashboards over a WebSocket, which needs the
# ASGI entry point rather than the WSGI one.
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Authentication
# The account is the phone number: everyone signs in with one, and the OTP
# that verifies it is sent there too.

AUTH_USER_MODEL = 'users.User'

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators
# One policy for every role. Registration, reset and change all run these.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': env_int('PASSWORD_MIN_LENGTH', 8)},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST framework
# Locked down by default: a view opts out with permission_classes, so a new
# endpoint cannot be left open by forgetting to add one.

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': env('THROTTLE_ANON', '60/min'),
        'user': env('THROTTLE_USER', '240/min'),
        # Guessing a password, an OTP or someone else's phone number all cost
        # a request, so the expensive paths get their own budget.
        'login': env('THROTTLE_LOGIN', '100/min'),
        'register': env('THROTTLE_REGISTER', '100/hour'),
        'otp': env('THROTTLE_OTP', '100/hour'),
        'password_reset': env('THROTTLE_PASSWORD_RESET', '10/hour'),
    },
    'EXCEPTION_HANDLER': 'Apps.users.exceptions.api_exception_handler',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env_int('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 15)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 30)),
    # A refresh spends the old token and mints a new one; the spent one is
    # blacklisted, so a stolen refresh token has one use at most.
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    # Falls back to the Django secret when no separate key is configured.
    'SIGNING_KEY': env('JWT_SIGNING_KEY') or SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# One-time codes. Fifteen minutes to use one, a minute between sends, and a
# ceiling on both guesses and sends so neither can be brute-forced.
OTP_LENGTH = env_int('OTP_LENGTH', 6)
OTP_EXPIRATION_MINUTES = env_int('OTP_EXPIRATION_MINUTES', 15)
OTP_RESEND_COOLDOWN_SECONDS = env_int('OTP_RESEND_COOLDOWN_SECONDS', 60)
OTP_MAX_VERIFY_ATTEMPTS = env_int('OTP_MAX_VERIFY_ATTEMPTS', 5)
OTP_MAX_SENDS_PER_HOUR = env_int('OTP_MAX_SENDS_PER_HOUR', 5)
# How long the token from a verified password-reset OTP stays good for.
PASSWORD_RESET_TOKEN_MAX_AGE_SECONDS = env_int('PASSWORD_RESET_TOKEN_MAX_AGE_SECONDS', 900)

# SMS delivery. `console` prints codes to the server log and is for local
# development only — see Apps/users/services/sms.py.
SMS_PROVIDER = env('SMS_PROVIDER', 'console')
SMS_API_KEY = env('SMS_API_KEY')
SMS_API_SECRET = env('SMS_API_SECRET')
SMS_SENDER_ID = env('SMS_SENDER_ID')
SMS_BASE_URL = env('SMS_BASE_URL')
SMS_TIMEOUT_SECONDS = env_int('SMS_TIMEOUT_SECONDS', 10)

# Try-on credits a new customer starts with. Mirrors the frontend's own
# STARTING_CREDITS so a fresh account reads the same on both sides.
STARTING_TRY_ON_CREDITS = env_int('STARTING_TRY_ON_CREDITS', 3)


# CORS
# The frontend is served from its own origin (Vite in development), so the
# browser needs these to reach the API.

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    # Localhost only. Testing on a phone means reaching this machine by its
    # LAN address, and that address is handed out by DHCP and changes — so it
    # belongs in `.env` on the machine it describes, never in a default here.
    'http://localhost:5173,http://localhost:5174,http://localhost:5175,http://127.0.0.1:5173'
)
# Tokens travel in the Authorization header, not in cookies, so credentialed
# requests are not needed and are left off.
CORS_ALLOW_CREDENTIALS = False

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS', ','.join(CORS_ALLOWED_ORIGINS))


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Timestamps are stored and compared in UTC. Opening hours are not timestamps:
# "10:00" means ten in the morning where the salon is, so "are they open now"
# is answered against the business timezone rather than this one.
TIME_ZONE = 'UTC'
BUSINESS_TIME_ZONE = env('BUSINESS_TIME_ZONE', 'Asia/Dhaka')

# Booking. The slot grid, how soon is too soon, how far ahead the diary opens,
# and the flat fee Eureka adds to a booking.
BOOKING_SLOT_MINUTES = env_int('BOOKING_SLOT_MINUTES', 15)
BOOKING_LEAD_MINUTES = env_int('BOOKING_LEAD_MINUTES', 45)
BOOKING_HORIZON_DAYS = env_int('BOOKING_HORIZON_DAYS', 60)
# The flat fee Eureka adds to a booking. The server is what charges it, and
# the frontend quotes it on the summary screen before the booking exists — so
# `PLATFORM_FEE` in services/frontend/src/constants must be the same number.
BOOKING_PLATFORM_FEE = env_int('BOOKING_PLATFORM_FEE', 50)

# Where booking events are fanned out between server processes. The in-memory
# layer is real but process-local: one `runserver` is fine, two workers behind
# a load balancer would each only reach the dashboards connected to them. Set
# REDIS_URL for anything beyond a single process.
REDIS_URL = env('REDIS_URL')
CHANNEL_LAYERS = {
    'default': (
        {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {'hosts': [REDIS_URL]},
        }
        if REDIS_URL
        else {'BACKEND': 'channels.layers.InMemoryChannelLayer'}
    )
}

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# Logging: OTP codes, passwords and tokens must never reach a log line. The
# services below log events, never the values themselves.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {'handlers': ['console'], 'level': env('DJANGO_LOG_LEVEL', 'INFO')},
}

# Behind TLS in production these keep sessions and CSRF cookies honest.
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
