# Generated by Django 6.1.1 on 2026-10-05 06:05

from django.db import migrations, models

#: What the seeded plans' own feature lists already promise: "3 AI try-ons per
#: month", "30 AI try-ons per month", "Unlimited AI hairstyle generation".
#: A plan an admin has added since starts at 0 and is set from Settings.
CREDITS = {'free': 3, 'basic': 30, 'advanced': None}


def set_credits(apps, schema_editor):
    SubscriptionTier = apps.get_model('subscriptions', 'SubscriptionTier')
    for slug, credits in CREDITS.items():
        SubscriptionTier.objects.filter(slug=slug).update(monthly_credits=credits)


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='monthly_credits',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.RunPython(set_credits, migrations.RunPython.noop),
    ]
