# Generated by Django 6.1.1 on 2026-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_seed_shared_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='steps',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
