# Generated by Django 6.1.1 on 2026-09-14 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_steps'),
        ('users', '0004_barberprofile_auto_accept_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Waiting for approval'), ('approved', 'Approved'), ('rejected', 'Turned down'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Moved to another time')], db_index=True, default='pending', max_length=12)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('blocked_from', models.DateTimeField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'The customer'), ('business', 'The business')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.barberprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.salonemployee')),
                ('rescheduled_from', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='bookings.appointment')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='users.salon')),
            ],
            options={
                'ordering': ('-starts_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('approved', 'Booking approved'), ('rejected', 'Booking turned down')], max_length=12)),
                ('to_phone', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Not sent yet'), ('sent', 'Handed to the gateway'), ('failed', 'The gateway refused it')], default='pending', max_length=10)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='bookings.appointment')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=0)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.appointment')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_items', to='services.service')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['salon', 'date'], name='bookings_ap_salon_i_4a8251_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['barber', 'date'], name='bookings_ap_barber__418430_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['customer', '-starts_at'], name='bookings_ap_custome_20da48_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', True), ('salon__isnull', False)), models.Q(('barber__isnull', False), ('salon__isnull', True)), _connector='OR'), name='appointment_has_exactly_one_business'),
        ),
    ]
