# Generated by Django 6.1.1 on 2026-09-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_appointment_guest_name_appointment_guest_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_with',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('card', 'Card')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
