# Generated by Django 6.1.1 on 2026-09-22 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_appointment_tenant'),
        ('tenants', '0001_initial'),
        ('users', '0006_remove_salonemployee_chair_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='bookings_ap_salon_i_4a8251_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='bookings_ap_barber__418430_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'date'], name='bookings_ap_tenant__cae7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'starts_at'], name='bookings_ap_tenant__f4caf1_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'status', 'date'], name='bookings_ap_tenant__27b3e1_idx'),
        ),
    ]
