import type { FlaggedContent } from '../types';
import { isoDaysAgo, isoHoursAgo } from './base';

/* Seven open items — the count the sidebar badge shows on first load. */
export const mockFlagged: FlaggedContent[] = [
  {
    id: 'MOD-501',
    contentType: 'photo',
    reporterId: 'USR-1078',
    reporterName: 'Sadia Rahman',
    reason: 'Not a hairstyle photo — looks like a random selfie used to game the portfolio.',
    dateReported: isoHoursAgo(3),
    status: 'under_review',
    content: {
      kind: 'photo',
      context: 'portfolio',
      uploaderName: 'Style Deck',
      caption: 'Fresh fade, walk-ins welcome!',
    },
  },
  {
    id: 'MOD-502',
    contentType: 'review',
    reporterId: 'BIZ-203',
    reporterName: 'Glow Beauty Lounge',
    reason: 'Review is abusive and names a staff member personally.',
    dateReported: isoHoursAgo(9),
    status: 'under_review',
    content: {
      kind: 'review',
      rating: 1,
      text: 'Worst service ever. The girl at the counter is useless and the whole place is a scam. Do not waste your money here.',
      authorName: 'Rakib Hasan',
      subjectName: 'Glow Beauty Lounge',
    },
  },
  {
    id: 'MOD-503',
    contentType: 'profile',
    reporterId: 'USR-1055',
    reporterName: 'Imran Hossain',
    reason: 'Business claims a Gulshan address that belongs to a different salon.',
    dateReported: isoDaysAgo(1, 14),
    status: 'needs_info',
    content: {
      kind: 'profile',
      profileName: 'Mirror Image Salon',
      profileType: 'salon',
      summary: 'Registered 4 days ago · 0 completed bookings · trade licence not uploaded.',
    },
  },
  {
    id: 'MOD-504',
    contentType: 'review',
    reporterId: 'BIZ-207',
    reporterName: 'Bindiya Salon',
    reason: 'Suspect this is a competitor leaving fake one-star reviews.',
    dateReported: isoDaysAgo(1, 19),
    status: 'under_review',
    content: {
      kind: 'review',
      rating: 1,
      text: 'Booked twice, never showed up. Terrible.',
      authorName: 'Anonymous customer',
      subjectName: 'Bindiya Salon',
    },
  },
  {
    id: 'MOD-505',
    contentType: 'photo',
    reporterId: 'USR-1063',
    reporterName: 'Tasnim Chowdhury',
    reason: 'Consultation photo shows another customer in the background without consent.',
    dateReported: isoDaysAgo(2, 11),
    status: 'under_review',
    content: {
      kind: 'photo',
      context: 'consultation',
      uploaderName: 'Nadia Sultana',
      caption: 'Reference for Saturday appointment',
    },
  },
  {
    id: 'MOD-506',
    contentType: 'profile',
    reporterId: 'USR-1090',
    reporterName: 'Fahim Reza',
    reason: 'Barber profile is using a stock photo and a phone number that never answers.',
    dateReported: isoDaysAgo(3, 16),
    status: 'under_review',
    content: {
      kind: 'profile',
      profileName: 'Sohel Rana',
      profileType: 'barber',
      summary: 'Joined 11 days ago · 2 bookings, both cancelled · phone unverified.',
    },
  },
  {
    id: 'MOD-507',
    contentType: 'review',
    reporterId: 'BIZ-211',
    reporterName: 'The Grooming Room',
    reason: 'Customer posted a full phone number in the review body.',
    dateReported: isoDaysAgo(4, 10),
    status: 'under_review',
    content: {
      kind: 'review',
      rating: 4,
      text: 'Decent cut. Call me on 017XXXXXXXX if you want the same barber, he does home visits too.',
      authorName: 'Zahid Hasan',
      subjectName: 'The Grooming Room',
    },
  },
  {
    id: 'MOD-498',
    contentType: 'review',
    reporterId: 'BIZ-202',
    reporterName: "Rafiq's Chair",
    reason: 'Profanity in the review text.',
    dateReported: isoDaysAgo(8, 12),
    status: 'rejected',
    adminNotes: 'Removed — breaches the community guidelines on abusive language.',
    content: {
      kind: 'review',
      rating: 2,
      text: '[removed by moderator]',
      authorName: 'Naimur Rahman',
      subjectName: "Rafiq's Chair",
    },
  },
  {
    id: 'MOD-499',
    contentType: 'photo',
    reporterId: 'USR-1072',
    reporterName: 'Israt Jahan',
    reason: 'Photo looked like a duplicate of another salon portfolio.',
    dateReported: isoDaysAgo(9, 15),
    status: 'approved',
    adminNotes: 'Verified with the owner — original photo, kept visible.',
    content: {
      kind: 'photo',
      context: 'portfolio',
      uploaderName: 'Aura Hair Lab',
      caption: 'Balayage before / after',
    },
  },
];
