# Generated by Django 6.1.1 on 2026-10-06 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_expiration_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('otp_resend_cooldown_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(3600)])),
                ('otp_max_verify_attempts', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('otp_max_sends_per_hour', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('password_min_length', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(64)])),
                ('password_reset_token_max_age_seconds', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(3600)])),
                ('jwt_access_token_lifetime_minutes', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1440)])),
                ('jwt_refresh_token_lifetime_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('throttle_anon', models.CharField(blank=True, max_length=20, null=True)),
                ('throttle_user', models.CharField(blank=True, max_length=20, null=True)),
                ('throttle_login', models.CharField(blank=True, max_length=20, null=True)),
                ('throttle_register', models.CharField(blank=True, max_length=20, null=True)),
                ('throttle_otp', models.CharField(blank=True, max_length=20, null=True)),
                ('throttle_password_reset', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_provider', models.CharField(blank=True, choices=[('console', 'Console (development only)'), ('http', 'HTTP gateway')], max_length=20, null=True)),
                ('sms_base_url', models.URLField(blank=True, max_length=300, null=True)),
                ('sms_sender_id', models.CharField(blank=True, max_length=20, null=True)),
                ('sms_timeout_seconds', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('join_url_base', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'platform settings',
                'verbose_name_plural': 'platform settings',
            },
        ),
    ]
