# Generated by Django 6.1.1 on 2026-09-14 09:57

import Apps.common.images
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_otpcode_debug_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', Apps.common.images.ImageRefField(blank=True, default='')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='users.barberprofile')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='users.salon')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', False), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('salon__isnull', False)), _connector='OR'), name='gallery_image_has_exactly_one_owner')],
            },
        ),
    ]
