# Generated by Django 6.1.1 on 2026-10-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tryonsettings',
            name='video_price_bdt',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
