# Generated by Django 6.1.1 on 2026-09-14 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_otpcode_debug_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')])),
                ('is_closed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='users.barberprofile')),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='users.salonemployee')),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='users.salon')),
            ],
            options={
                'ordering': ('weekday',),
            },
        ),
        migrations.CreateModel(
            name='WorkingInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='schedules.workingday')),
            ],
            options={
                'ordering': ('start',),
            },
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('barber__isnull', True), ('employment__isnull', True), ('salon__isnull', False)), models.Q(('barber__isnull', False), ('employment__isnull', True), ('salon__isnull', True)), models.Q(('barber__isnull', True), ('employment__isnull', False), ('salon__isnull', True)), _connector='OR'), name='working_day_has_exactly_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(condition=models.Q(('salon__isnull', False)), fields=('salon', 'weekday'), name='unique_salon_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(condition=models.Q(('barber__isnull', False)), fields=('barber', 'weekday'), name='unique_barber_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workingday',
            constraint=models.UniqueConstraint(condition=models.Q(('employment__isnull', False)), fields=('employment', 'weekday'), name='unique_employment_weekday'),
        ),
    ]
